const ecbNatIDs = [
    { type: "AE_BL_CD", rank: 1, isoCountry: "AE", name: "Business License (BL) Number", shortName: "BL", class: "Business register number", regExp: "\\d{4,5}" }, 
    { type: "AR_CUIT_CD", rank: 1, isoCountry: "AR", name: "Argentina Unique Tax Identification Key (CUIT/CUIL)", shortName: "CUIT", class: "Tax code", regExp: "\\d{2}-\\d{8}-\\d{1}" }, 
    { type: "AT_FB_CD", rank: 2, isoCountry: "AT", name: "Firmenbuchnummer", shortName: "FB-Nr.", class: "Business register number", regExp: "\\d{1,6}[A-Za-z]\\d{0,3}" }, 
    { type: "AT_GEM_CD", rank: 4, isoCountry: "AT", name: "Gemeindenummer", shortName: "Gemeinde-Nr.", class: "Public sector entity identifier", regExp: "\\d{5}" }, 
    { type: "AT_IDENT_CD", rank: 1, isoCountry: "AT", name: "Identnummer", shortName: "", class: "NCB identifier", regExp: "\\d{1,8}" }, 
    { type: "AT_LAE_CD", rank: 5, isoCountry: "AT", name: "Ländernummer", shortName: "Laender-Nr.", class: "Public sector entity identifier", regExp: "\\d" }, 
    { type: "AT_NOTAP_CD", rank: 6, isoCountry: "AT", name: "Not applicable", shortName: "", class: "", regExp: "" }, 
    { type: "AT_ZVR_CD", rank: 3, isoCountry: "AT", name: "Vereinsregisternummer", shortName: "ZVR", class: "Register of associations", regExp: "\\d{1,10}" }, 
    { type: "AU_ABN_CD", rank: 1, isoCountry: "AU", name: "Australia Business Number", shortName: "", class: "Business register number", regExp: "\\d{2} \\d{3} \\d{3} \\d{3}" }, 
    { type: "AU_ACN_CD", rank: 2, isoCountry: "AU", name: "Australia Company Number", shortName: "", class: "Business register number", regExp: "\\d{3} \\d{3} \\d{3}" }, 
    { type: "BA_JIB_CD", rank: 2, isoCountry: "BA", name: "Jedinstveni identifikacioni broj (JIB)", shortName: "JIB", class: "Trade register number", regExp: "\\d{13}" }, 
    { type: "BA_MBS_CD", rank: 1, isoCountry: "BA", name: "Matični broj subjekta - MBS", shortName: "MBS", class: "Business register number", regExp: "\\d{1,2}-\\d{3,5}|\\d{1}-\\d{4}-\\d{2}|\\d{2}-\\d{2}-\\d{4}-\\d{2}" }, 
    { type: "BA_PIB_CD", rank: 3, isoCountry: "BA", name: "Poreski identifikacioni broj (PIB)", shortName: "PIB", class: "Tax code", regExp: "\\d{12}" }, 
    { type: "BE_OND_CD", rank: 1, isoCountry: "BE", name: "Numéro d'entreprise / Ondernemingsnummer / Unternehmensnummer", shortName: "", class: "Business register number", regExp: "[0,1]\\d{9}" }, 
    { type: "BG_BULSTAT_CD", rank: 1, isoCountry: "BG", name: "Единен идентификационен код (по БУЛСТАТ)", shortName: "ЕИК по БУЛСТАТ", class: "Public registry identification number", regExp: "\\d{13}|\\d{10}|\\d{9}" }, 
    { type: "BG_UIC_CD", rank: 1, isoCountry: "BG", name: "Единен (Персонален) идентификационен код", shortName: "ЕИК", class: "Trade register number", regExp: "\\d{13}|\\d{9}" }, 
    { type: "BG_VAT_CD", rank: 2, isoCountry: "BG", name: "Идентификационен номер по ДДС ", shortName: "", class: "VAT number", regExp: "(BG)\\d{9,10}" }, 
    { type: "BM_RN_CD", rank: 1, isoCountry: "BM", name: "Bermuda Registration Number", shortName: "", class: "Business register number", regExp: "\\d{4,5}" }, 
    { type: "BR_CNPJ_CD", rank: 1, isoCountry: "BR", name: "Cadastro Nacional da Pessoa Jurídica", shortName: "CNPJ", class: "Identification number", regExp: "\\d{2}.\\d{3}.\\d{3}\/\\d{4}-\\d{2}" }, 
    { type: "BS_NBR_CD", rank: 1, isoCountry: "BS", name: "Bahamas national business registern number", shortName: "", class: "Business register number", regExp: "\\d{5,7}" }, 
    { type: "BY_NBR_CD", rank: 1, isoCountry: "BY", name: "Registration number (Регистрационный номер)", shortName: "", class: "Business register number", regExp: "\\d{9}" }, 
    { type: "BZ_TIN_CD", rank: 1, isoCountry: "BZ", name: "TIN (Tax ID Number)", shortName: "TIN", class: "Tax code", regExp: "\\d{6}" }, 
    { type: "CA_BN_CD", rank: 1, isoCountry: "CA", name: "Business Number / Federal Tax ID", shortName: "", class: "Tax code", regExp: "\\d{9}" }, 
    { type: "CA_REG_ID_CD", rank: 2, isoCountry: "CA", name: "Registration Number", shortName: "", class: "Business register number", regExp: "\\d{7}|(BC\\d{7})" }, 
    { type: "CH_ID_CD", rank: 2, isoCountry: "CH", name: "Business register number", shortName: "", class: "Business register number", regExp: "(CH)\-\\d{3}\-\\d{7}-\\d{1}" }, 
    { type: "CH_NUMMER", rank: 3, isoCountry: "CH", name: "Business register number", shortName: "", class: "Business register number", regExp: "(CH)-\\d{3}\.\\d{1}\.\\d{3}\.\\d{3}\-\\d{1}" }, 
    { type: "CH_UID_CD", rank: 1, isoCountry: "CH", name: "Unternehmens-Identifikationsnummer", shortName: "UID", class: "Tax code", regExp: "(CHE)-\\d{3}\.\\d{3}\.\\d{3}" }, 
    { type: "CL_RUT_CD", rank: 1, isoCountry: "CL", name: "Rol Único Tributario ", shortName: "", class: "Tax code", regExp: "\\d{2}.\\d{3}.\\d{3}-[K0-9]|\\d{8}-[K0-9]" }, 
    { type: "CN_CC_CD", rank: 1, isoCountry: "CN", name: "Credibility Code, or USCN code", shortName: "", class: "Tax code", regExp: "[A-Z0-9]{18}" }, 
    { type: "CO_NIT_CD", rank: 1, isoCountry: "CO", name: "Número De Identificación Tributaria (NIT)", shortName: "NIT", class: "Tax code", regExp: "\\d{9}-\\d{1}" }, 
    { type: "CY_CBCID_CD", rank: 1, isoCountry: "CY", name: "CBC internal code", shortName: "CBC ID code", class: "NCB identifier", regExp: "[A-Z]{2}\\d{1,8}" }, 
    { type: "CY_DRCOR_CD", rank: 1, isoCountry: "CY", name: "Αριθμός Εγγραφής στο Τμήμα Εφόρου Εταιρειών και Επίσημου Παραλήπτη ", shortName: "ΑΡ. ΕΓΓΡΑΦΗΣ", class: "Business register number", regExp: "(C|O|P)\\d{1,8}" }, 
    { type: "CY_GG_CD", rank: 1, isoCountry: "CY", name: "Αριθμός μονάδων γενικής κυβέρνησης", shortName: "GG code", class: "General Government Unit identifier", regExp: "(S13)\\d{8}" }, 
    { type: "CY_IF_CD", rank: 2, isoCountry: "CY", name: "Investment Fund identifier", shortName: "IF code", class: "Investment Fund identifier ", regExp: "(CYIF)\\d{4}" }, 
    { type: "CY_OTHER_CD", rank: 6, isoCountry: "CY", name: "Other national identifier", shortName: "", class: "", regExp: "" }, 
    { type: "CY_PF_CD", rank: 1, isoCountry: "CY", name: "Pension Fund code", shortName: "PF code", class: "Pension Fund identifier", regExp: "(PF)\\d{1,4}" }, 
    { type: "CY_TIC_CD", rank: 4, isoCountry: "CY", name: "Αριθμός φορολογικής ταυτότητας ", shortName: "T.I.C. code", class: "Tax code", regExp: "\\d{8}[A-Z]" }, 
    { type: "CY_VAT_CD", rank: 3, isoCountry: "CY", name: "Αριθμός Εγγραφής Φ.Π.Α.", shortName: "ΦΠΑ", class: "VAT number", regExp: "(0|1|3|4|5|9)\\d{7}[A-Z]" }, 
    { type: "CZ_ICO_CD", rank: 1, isoCountry: "CZ", name: "Identifikační číslo osoby", shortName: "ICO", class: "Business register number", regExp: "\\d{8}" }, 
    { type: "CZ_NID_CD", rank: 2, isoCountry: "CZ", name: "Náhradní identifikační číslo", shortName: "NID/KIC", class: "Investment/Pension fund identifier", regExp: "\\d{10}|\\d{8}" }, 
    { type: "DE_NOTAP_CD", rank: 4, isoCountry: "DE", name: "Kein Registereintrag (Not applicable)", shortName: "", class: "", regExp: "" }, 
    { type: "DE_TAX_CD", rank: 3, isoCountry: "DE", name: "Steuernummer", shortName: "", class: "Tax code", regExp: "\\d{13}" }, 
    { type: "DE_TRD_RGSTR_CD", rank: 1, isoCountry: "DE", name: "- Genossenschaftsregister,  - Handelsregister Abteilung A, - Handelsregister Abteilung B, - Partnerschaftsregister, - Vereinsregister ", shortName: "GnR, HRA, HRB, PR, VR ", class: "Trade register number", regExp: "((G(n|N)R)|(HRA)|(HRB)|(PR)|(VR))\\d{1,6}[A-Z]{0,5}-[A-Z]\\d{4} " }, 
    { type: "DE_VAT_CD", rank: 2, isoCountry: "DE", name: "Umsatzsteuer-Identifikationsnummer", shortName: "", class: "VAT number", regExp: "DE\\d{9}" }, 
    { type: "DK_CVR_CD", rank: 1, isoCountry: "DK", name: "CVR-nummer", shortName: "", class: "Business register number", regExp: "\\d{8}" }, 
    { type: "DK_FT_CD", rank: 2, isoCountry: "DK", name: "FT-nummer", shortName: "", class: "National Supervisory Authority code", regExp: "\\d+(-\\d+)?" }, 
    { type: "DK_NOTAP_CD", rank: 4, isoCountry: "DK", name: "Not applicable", shortName: "", class: "", regExp: "" }, 
    { type: "DK_SE_CD", rank: 3, isoCountry: "DK", name: "SE-nummer", shortName: "", class: "VAT number", regExp: "\\d{8}" }, 
    { type: "EC_RUC_CD", rank: 1, isoCountry: "EC", name: "Número de Registro Unico de Contribuyentes (RUC)", shortName: "RUC", class: "Tax code", regExp: "\\d{13}" }, 
    { type: "EE_FON_CD", rank: 1, isoCountry: "EE", name: "Aruandja kood", shortName: "fondi kood", class: "Investment/Pension fund identifier", regExp: "\\d{1,4}" }, 
    { type: "EE_RG_CD", rank: 1, isoCountry: "EE", name: "Äriregistri kood", shortName: "rg-kood", class: "Business register number", regExp: "\\d{8}" }, 
    { type: "ES_NIF_CD", rank: 1, isoCountry: "ES", name: "Código de Identificación Fiscal", shortName: "NIF", class: "Tax code", regExp: "[A-Z0-9]{9}" }, 
    { type: "FI_ALV_CD", rank: 2, isoCountry: "FI", name: "Arvonlisäverotunniste", shortName: "ALV-tunnus", class: "VAT number", regExp: "(FI)\\d{8}" }, 
    { type: "FI_NOTAP_CD", rank: 4, isoCountry: "FI", name: "Not applicable", shortName: "", class: "", regExp: "" }, 
    { type: "FI_SIRA_CD", rank: 3, isoCountry: "FI", name: "Rahastotunnus", shortName: "SIRA-tunnus", class: "Investment/Pension fund identifier", regExp: "\\d{8}(#)\\d{3}" }, 
    { type: "FI_Y_CD", rank: 1, isoCountry: "FI", name: "Yritys- ja yhteisötunnus / Y-tunnus", shortName: "Y-tunnus", class: "Business register number", regExp: "\\d{7}-?\\d" }, 
    { type: "FR_CIB", rank: 1, isoCountry: "FR", name: "Code interbancaire", shortName: "CIB", class: "National Supervisory Authority code", regExp: "\\d{5}" }, 
    { type: "FR_IF_CD", rank: 1, isoCountry: "FR", name: "Investment Fund identifier", shortName: "IF code", class: "Investment Fund identifier ", regExp: "(FR)[A-Z0-9]{10}" }, 
    { type: "FR_RNA_CD", rank: 1, isoCountry: "FR", name: "Numéro RNA", shortName: "RNA", class: "Association register number", regExp: "[A-Z]\\d{9}" }, 
    { type: "FR_SIREN_CD", rank: 1, isoCountry: "FR", name: "Code SIREN", shortName: "SIREN", class: "Business register number", regExp: "\\d{9}" }, 
    { type: "GB_CRN_CD", rank: 1, isoCountry: "GB", name: "Company Registration Number", shortName: "CRN", class: "Business register number", regExp: "[A-Z0-9]{8}" }, 
    { type: "GB_FSR_CD", rank: 3, isoCountry: "GB", name: "Financial Services Register code", shortName: "FSR", class: "National Supervisory Authority code", regExp: "\\d{6}" }, 
    { type: "GB_UTR_CD", rank: 2, isoCountry: "GB", name: "Unique taxpayer reference", shortName: "UTR", class: "Tax code", regExp: "\\d{10}|\\d{9}(K)" }, 
    { type: "GB_VAT_CD", rank: 4, isoCountry: "GB", name: "VAT number", shortName: "VAT GB", class: "VAT number", regExp: "(GB)\\d{9}|(GB)\\d{12}|(GBGD)\\d{3}|(GBHA)\\d{3}" }, 
    { type: "GEN_IPF_CD", rank: 9, isoCountry: "", name: "Investment/Pension fund identifier", shortName: "", class: "Investment/Pension fund identifier", regExp: "" }, 
    { type: "GEN_NBR_ENTTY_CD", rank: 3, isoCountry: "", name: "Business register number", shortName: "", class: "Business register number", regExp: "" }, 
    { type: "GEN_NCB_ENTTY_CD", rank: 6, isoCountry: "", name: "National Central Bank identifier", shortName: "", class: "NCB identifier", regExp: "" }, 
    { type: "GEN_NOTAP_CD", rank: 0, isoCountry: "", name: "Not applicable", shortName: "", class: "", regExp: "" }, 
    { type: "GEN_NSA_ENTTY_CD", rank: 7, isoCountry: "", name: "National supervisory authority code", shortName: "", class: "National Supervisory Authority code", regExp: "" }, 
    { type: "GEN_NSI_ENTTY_CD", rank: 5, isoCountry: "", name: "National Statistical Institute number", shortName: "", class: "National Statistical Institute number", regExp: "" }, 
    { type: "GEN_OTHER_CD", rank: 10, isoCountry: "", name: "Other (please specify)", shortName: "", class: "", regExp: "" }, 
    { type: "GEN_PS_CD", rank: 8, isoCountry: "", name: "Public sector entity identifier", shortName: "", class: "Public sector entity identifier", regExp: "" }, 
    { type: "GEN_TAX_CD", rank: 2, isoCountry: "", name: "Tax code", shortName: "", class: "Tax code", regExp: "" }, 
    { type: "GEN_TRD_RGSTR_ENTTY_CD", rank: 4, isoCountry: "", name: "Trade register number", shortName: "", class: "Trade register number", regExp: "" }, 
    { type: "GEN_VAT_CD", rank: 1, isoCountry: "", name: "VAT number", shortName: "", class: "VAT number", regExp: "" }, 
    { type: "GG_RN_CD", rank: 1, isoCountry: "GG", name: "Entity Reg Number", shortName: "", class: "Business register number", regExp: "\\d{5}" }, 
    { type: "GR_AFM_CD", rank: 1, isoCountry: "GR", name: "Arithmós Forologikou Mitroou A-Fi-Mi  Αριθμός Φορολογικού Μητρώου Α.Φ.Μ.", shortName: "AFM", class: "Tax code", regExp: "\\d{9}" }, 
    { type: "GR_IMO_CD", rank: 1, isoCountry: "GR", name: "International Maritime Organisation number", shortName: "IMO", class: "Trade register number", regExp: "\\d{7}" }, 
    { type: "HK_CR_CD", rank: 1, isoCountry: "HK", name: "Corporate Registry Number", shortName: "CR-No.", class: "Business register number", regExp: "[A-Z]{0,1}\\d{7}" }, 
    { type: "HR_MB_CD", rank: 2, isoCountry: "HR", name: "Matični broj poslovnog subjekta", shortName: "MB", class: "Business register number", regExp: "\\d{8}" }, 
    { type: "HR_MBS_CD", rank: 3, isoCountry: "HR", name: "Matični broj subjekta trgovačkog suda", shortName: "MBS", class: "Trade register number", regExp: "[0-1]\\d{8}" }, 
    { type: "HR_OIB_CD", rank: 1, isoCountry: "HR", name: "Osobni identifikacijski broj", shortName: "OIB", class: "Tax code", regExp: "\\d{11}" }, 
    { type: "HU_CEG_CD", rank: 1, isoCountry: "HU", name: "Cégjegyzékszám ", shortName: "", class: "Trade register number", regExp: "\\d{2}(-)\\d{2}(-)\\d{6}" }, 
    { type: "HU_FB_CD", rank: 1, isoCountry: "HU", name: "FB kód", shortName: "FB kód", class: "Investment fund identifier", regExp: "(FB)\\d{6}|(FB)\\d{3}[A-Z]\\d{2}" }, 
    { type: "HU_KOZ_CD", rank: 1, isoCountry: "HU", name: "Közösségi adószám", shortName: "", class: "VAT number", regExp: "(HU)\\d{8}" }, 
    { type: "HU_TOR_CD", rank: 1, isoCountry: "HU", name: "Törzsszám", shortName: "", class: "Tax code", regExp: "\\d{8}" }, 
    { type: "ID_NPWP_CD", rank: 1, isoCountry: "ID", name: "Nomor Pokok Wajib Pajak (NPWP)", shortName: "NPWP", class: "Tax code", regExp: "\\d{2}.\\d{3}.\\d{3}.\\d{1}-\\d{3}.\\d{3}" }, 
    { type: "IE_CRO_CD", rank: 1, isoCountry: "IE", name: "Company Registration Office number", shortName: "CRO number", class: "Trade register number", regExp: "[1-9]\\d{1,6}" }, 
    { type: "IE_GOV_CD", rank: 2, isoCountry: "IE", name: "Government bodies identifier", shortName: "", class: "", regExp: "(GV)\\d{4}|(LA)\\d{3}" }, 
    { type: "IE_NOTAP_CD", rank: 4, isoCountry: "IE", name: "Not applicable", shortName: "", class: "", regExp: "" }, 
    { type: "IE_VAT_CD", rank: 3, isoCountry: "IE", name: "VAT number", shortName: "VAT IE", class: "VAT number", regExp: "(IE)[A-Z0-9]{1,9}" }, 
    { type: "IL_TAX_CD", rank: 1, isoCountry: "IL", name: "Israeli Tax Identification Number", shortName: "", class: "Tax code", regExp: "\\d{9}" }, 
    { type: "IM_RN_CD", rank: 1, isoCountry: "IM", name: "Isel of Man Registration Number", shortName: "", class: "Trade register number", regExp: "\\d{6}[A-Z]" }, 
    { type: "IM_TAX_CD", rank: 2, isoCountry: "IM", name: "Tax Reference Number ", shortName: "", class: "Tax code", regExp: "[H,C,X]\\d{6}-\\d{2}" }, 
    { type: "IN_CIN_CD", rank: 1, isoCountry: "IN", name: "Corporate identity number", shortName: "CIN", class: "Business register number", regExp: "[A-Z0-9]{21}" }, 
    { type: "IN_PAN_CD", rank: 2, isoCountry: "IN", name: "Permanent Account Number", shortName: "PAN", class: "Tax code", regExp: "[A-Z0-9]{10}" }, 
    { type: "IT_CCIAA_CD", rank: 2, isoCountry: "IT", name: "Numero d'iscrizione camerale", shortName: "CCIAA+REA", class: "Trade register number", regExp: "[A-Z]{2}\\d{7}" }, 
    { type: "IT_CF_CD", rank: 1, isoCountry: "IT", name: "Codice fiscale", shortName: "CF", class: "Tax code", regExp: "\\d{11}" }, 
    { type: "IT_UCITS_CD", rank: 1, isoCountry: "IT", name: "Codice OICR", shortName: "UCITS", class: "Investment/Pension fund identifier", regExp: "\\d{1,7}" }, 
    { type: "JE_TAX_CD", rank: 1, isoCountry: "JE", name: "Tax reference number", shortName: "", class: "Tax code", regExp: "[A-Z][A-Z]\\d{5}" }, 
    { type: "JP_CN_CD", rank: 1, isoCountry: "JP", name: "Corporate Number", shortName: "", class: "Business register number", regExp: "\\d{13}" }, 
    { type: "KR_TIN_CD", rank: 1, isoCountry: "KR", name: "Business registration number (TIN)", shortName: "TIN", class: "Business register number", regExp: "\\d{3}-\\d{2}-\\d{5}" }, 
    { type: "LI_FL_CD", rank: 1, isoCountry: "LI", name: "FL nummer - Registration number", shortName: "", class: "Business register number", regExp: "(FL)-\\d{4}.\\d{3}.\\d{3}-\\d{1}" }, 
    { type: "LT_INV_CD", rank: 2, isoCountry: "LT", name: "Investicinio/ pensijų fondo kodas", shortName: "", class: "Investment/Pension fund identifier", regExp: "[A-Z]\\d{3}|(SF)\\d{3}|[A-Z]{3}-\\d{2}\/\\d{2}|[A-Z]{3}-[A-Z]{4}" }, 
    { type: "LT_JAR_CD", rank: 1, isoCountry: "LT", name: "Juridinių asmenų registro kodas", shortName: "JAR kodas", class: "Business register number", regExp: "\\d{9}" }, 
    { type: "LU_IF_CD", rank: 1, isoCountry: "LU", name: "Investment Fund identifier", shortName: "IF code", class: "Investment Fund identifier ", regExp: "[A-Z]\\d{6}[C]\\d{5}" }, 
    { type: "LU_NOTAP_CD", rank: 2, isoCountry: "LU", name: "Not applicable", shortName: "", class: "", regExp: "" }, 
    { type: "LU_RCS_CD", rank: 1, isoCountry: "LU", name: "Numéro registre de commerce et des sociétés (RCS)", shortName: "RCS", class: "Trade register number", regExp: "[A-Z]\\d+" }, 
    { type: "LU_VAT_CD", rank: 1, isoCountry: "LU", name: "Public sector entity identifier", shortName: "VAT", class: "VAT number", regExp: "\\d{8}" }, 
    { type: "LV_FON_CD", rank: 4, isoCountry: "LV", name: "Ieguldījumu fondu /pensiju fondu kods", shortName: "", class: "NCB identifier", regExp: "(LV)\\d{11}|(LVAF)\\d{3}(A|B|\\d{1})\\d{2}|(LVB)\\d{6}|(LVIF)\\d{3}(A|B|C|D|E|F|\\d{1})\\d{2}|(LVVF)\\d{6}" }, 
    { type: "LV_NBR_CD", rank: 1, isoCountry: "LV", name: "Komersanta reģistrācijas numurs Latvijas Republikas Uzņēmumu reģistra komercreģistrā", shortName: "NBR", class: "Business register number", regExp: "\\d{11}" }, 
    { type: "LV_VAT_CD", rank: 2, isoCountry: "LV", name: "Pievienotās vērtības nodokļa (PVN) maksātāja kods", shortName: "", class: "VAT number", regExp: "(LV)\\d{11}" }, 
    { type: "MC_CIB", rank: 1, isoCountry: "MC", name: "Code interbancaire", shortName: "CIB", class: "National Supervisory Authority code", regExp: "\\d{5}" }, 
    { type: "MC_NIS_CD", rank: 2, isoCountry: "MC", name: "Numéro d'Identification Statistique", shortName: "NIS", class: "Business register number", regExp: "\\d{2,4}[A-Z]\\d{5}" }, 
    { type: "MC_RCI_CD", rank: 1, isoCountry: "MC", name: "Numéro RCI", shortName: "RCI", class: "Trade register number", regExp: "\\d{2}[A-Z]{1,3}\\d{5}" }, 
    { type: "MH_NBR_CD", rank: 1, isoCountry: "MH", name: "Business register number", shortName: "", class: "Business register number", regExp: "\\d{4,6}" }, 
    { type: "MT_CNUM_CD", rank: 1, isoCountry: "MT", name: "Malta Business Registry company registration number ", shortName: "", class: "Malta Business Registry company registration number", regExp: "" }, 
    { type: "MT_OLE_CD", rank: 3, isoCountry: "MT", name: "Other Legal Entities code", shortName: "", class: "Other Legal Identifier", regExp: "" }, 
    { type: "MT_VAT_CD", rank: 2, isoCountry: "MT", name: "VAT number", shortName: "", class: "VAT number", regExp: "\\d{8}" }, 
    { type: "MX_RFC_CD", rank: 1, isoCountry: "MX", name: "Clave en el Registro Federal de Contribuyentes", shortName: "RFC", class: "Tax code", regExp: "[A-Z]{3}-\\d{6}-[A-Z0-9]{3}" }, 
    { type: "MY_CRN_CD", rank: 1, isoCountry: "MY", name: "Company Registration Number Old", shortName: "", class: "Business register number", regExp: "\\d{6}-[A-Z]" }, 
    { type: "NC_NBR_CD", rank: 1, isoCountry: "NC", name: "Business register number (RID7)", shortName: "RID7", class: "Business register number", regExp: "\\d{7}" }, 
    { type: "NL_KVK_CD", rank: 1, isoCountry: "NL", name: "Kamer van Koophandel nummer", shortName: "KvK-nummer", class: "Trade register number", regExp: "\\d{8}" }, 
    { type: "NL_RSIN_CD", rank: 2, isoCountry: "NL", name: "Rechtspersonen Samenwerkingsverbanden Informatie nummer", shortName: "RSIN", class: "Tax code", regExp: "\\d{9}" }, 
    { type: "NO_NBR_CD", rank: 1, isoCountry: "NO", name: "Organization number, Brønnøysund Register ", shortName: "", class: "Business register number", regExp: "\\d{9}" }, 
    { type: "PA_RUC_CD", rank: 1, isoCountry: "PA", name: "Single Taxpayer Registry (Registro Único de Contribuyente RUC)", shortName: "RUC", class: "Tax code", regExp: "" }, 
    { type: "PE_RUC_CD", rank: 1, isoCountry: "PE", name: "Registro Único de Contribuyente (RUC)", shortName: "RUC", class: "Tax code", regExp: "\\d{11}" }, 
    { type: "PL_KRS_CD", rank: 2, isoCountry: "PL", name: "Numer w Krajowym Rejesrze Sądowym (KRS)", shortName: "KRS", class: "Business register number", regExp: "\\d+" }, 
    { type: "PL_NIP_CD", rank: 3, isoCountry: "PL", name: "Numer Identyfikacji Podatkowej", shortName: "NIP", class: "Tax code", regExp: "\\d{10}" }, 
    { type: "PL_REGON_CD", rank: 1, isoCountry: "PL", name: "Numer identyfikacyjny REGON", shortName: "REGON number", class: "Business register number", regExp: "\\d{14}|\\d{9}" }, 
    { type: "PL_VAT_CD", rank: 4, isoCountry: "PL", name: "Numer Identyfikacji Podatkowej NIP z prefixem PL", shortName: "VAT UE", class: "VAT number", regExp: "(PL)\\d{10}" }, 
    { type: "PT_ASF_CD", rank: 4, isoCountry: "PT", name: "Código da Autoridade de Supervisão de Seguros e Fundos de Pensões", shortName: "ASF", class: "National Supervisory Authority code", regExp: "\\d{1,4}" }, 
    { type: "PT_FSA_CD", rank: 2, isoCountry: "PT", name: "Código de Agente Financeiro ", shortName: "BdP", class: "National Supervisory Authority code", regExp: "\\d{1,6}" }, 
    { type: "PT_IF_CD", rank: 3, isoCountry: "PT", name: "Código da Comissão do Mercado de Valores Mobiliários", shortName: "CMVM", class: "National Supervisory Authority code", regExp: "\\d{1,8}" }, 
    { type: "PT_NIF_CD", rank: 1, isoCountry: "PT", name: "Número de Identificação de Pessoa Coletiva", shortName: "NIF/NIPC", class: "Tax code", regExp: "\\d{9}" }, 
    { type: "RO_CUI_CD", rank: 1, isoCountry: "RO", name: "Codul unic de identificare fiscală", shortName: "CUI", class: "Tax code", regExp: "(RO)\\d{1,10}" }, 
    { type: "RO_TAX_CD", rank: 2, isoCountry: "RO", name: "Identificatorul aferent taxei pe valoarea adaugata", shortName: "", class: "VAT number", regExp: "(RO)\\d{1,10}" }, 
    { type: "RO_TRN_CD", rank: 3, isoCountry: "RO", name: "Numarul de inregistrare la registrul comertului", shortName: "", class: "Trade register number", regExp: "(J)\\d{2}\/\\d{1,9}\/\\d{4}" }, 
    { type: "RS_MB_CD", rank: 2, isoCountry: "RS", name: "Matični broj", shortName: "", class: "Business register number", regExp: "\\d{8}" }, 
    { type: "RS_PIB_CD", rank: 1, isoCountry: "RS", name: "Poreski identifikacioni broj PIB", shortName: "PIB", class: "Tax code", regExp: "[1-9]\\d{8}" }, 
    { type: "RU_INN_CD", rank: 1, isoCountry: "RU", name: "Taxpayer Personal Identification Number", shortName: "INN", class: "Tax code", regExp: "\\d{10}" }, 
    { type: "RU_OGRN_CD", rank: 2, isoCountry: "RU", name: "Основной государственный регистрационный номер", shortName: "OGRN", class: "Business register number", regExp: "\\d{13}" }, 
    { type: "SE_FIN_CD", rank: 2, isoCountry: "SE", name: "Finansinspektionens institutnummer", shortName: "", class: "National Supervisory Authority code", regExp: "\\d{5}" }, 
    { type: "SE_MOM_CD", rank: 3, isoCountry: "SE", name: "Momsregistreringsnummer", shortName: "", class: "VAT number", regExp: "(SE)\\d{12}" }, 
    { type: "SE_NOTAP_CD", rank: 4, isoCountry: "SE", name: "Not applicable", shortName: "", class: "", regExp: "" }, 
    { type: "SE_ORG_CD", rank: 1, isoCountry: "SE", name: "Organisationsnummer", shortName: "", class: "Business register number", regExp: "\\d{2}[2-9]\\d{3}-?\\d{4}" }, 
    { type: "SG_ROB_CD", rank: 1, isoCountry: "SG", name: "UEN – Business (ROB)", shortName: "ROB", class: "Tax code", regExp: "(\\d{9}[A-Z])|([A-Z]\\d{2}[A-Z]{2}\\d{4}[A-Z])" }, 
    { type: "SI_DAV_CD", rank: 2, isoCountry: "SI", name: "Davčna številka", shortName: "", class: "Tax code", regExp: "\\d{8}" }, 
    { type: "SI_DDV_CD", rank: 3, isoCountry: "SI", name: "ID za DDV", shortName: "", class: "VAT number", regExp: "(SI)\\d{8}" }, 
    { type: "SI_MAT_CD", rank: 1, isoCountry: "SI", name: "Matična številka", shortName: "", class: "Business register number", regExp: "\\d{10}" }, 
    { type: "SK_ICO_CD", rank: 1, isoCountry: "SK", name: "Identifikačné číslo organizácie", shortName: "ICO", class: "Business register number", regExp: "\\d{8}[a-z]{0,1}" }, 
    { type: "SK_IF_CD", rank: 1, isoCountry: "SK", name: "Kód investičného fondu", shortName: "", class: "Investment Fund identifier ", regExp: "(SK)\\d{8}[A-Z]{3}\\d{2}" }, 
    { type: "SM_COE_CD", rank: 1, isoCountry: "SM", name: " Codice operatore economico (C.O.E.)", shortName: "C.O.E.", class: "Tax code", regExp: "\\d{5}" }, 
    { type: "TH_NBR_CD", rank: 1, isoCountry: "TH", name: "Thailand Business register number", shortName: "", class: "Business register number", regExp: "\\d{13}" }, 
    { type: "TR_VKN_CD", rank: 1, isoCountry: "TR", name: "Vergi Kimlik Numarası", shortName: "", class: "Tax code", regExp: "\\d{1,10}" }, 
    { type: "TW_TAX_CD", rank: 1, isoCountry: "TW", name: "統一編號 (Tax number)", shortName: "", class: "Tax code", regExp: "\\d{8}" }, 
    { type: "US_CIK_CD", rank: 2, isoCountry: "US", name: "Central Index Key", shortName: "CIK", class: "", regExp: "\\d{10}" }, 
    { type: "US_DSFN_CD", rank: 3, isoCountry: "US", name: "Delaware State File Number", shortName: "", class: "Business register number", regExp: "\\d{6,7}" }, 
    { type: "US_EIN_CD", rank: 1, isoCountry: "US", name: "Employer Identification Number", shortName: "EIN", class: "Tax code", regExp: "\\d{2}-\\d{7}" }, 
    { type: "UY_RUT_CD", rank: 1, isoCountry: "UY", name: "Registro Único Tributario (RUT)", shortName: "RUT", class: "Tax code", regExp: "\\d{12}" }
];

const ecbNatIDsDnbCodes = [
    { ecbType: 'NL_KVK_CD', dnbCode: 6256 },
    { ecbType: 'NL_RSIN_CD', dnbCode: 23097 },
    { ecbType: 'BE_OND_CD', dnbCode: 800 },
    { ecbType: 'LU_VAT_CD', dnbCode: 480 },
    { ecbType: 'LU_RCS_CD', dnbCode: 3827 },
    { ecbType: 'FR_SIREN_CD', dnbCode: 2078 },
    { ecbType: 'FR_SIREN_CD', dnbCode: 2078 },
    { ecbType: 'GB_CRN_CD', dnbCode: 2541 },
    { ecbType: 'IE_CRO_CD', dnbCode: 9134 },
];

ecbNatIDs.forEach(id => {
    const arrDnbCodes = ecbNatIDsDnbCodes.filter(ecbNatIDsDnbCode => id.type === ecbNatIDsDnbCode.ecbType);

    if(arrDnbCodes.length) { id.dnbCode = arrDnbCodes[0].dnbCode }

    if(id.regExp) { id.objRegExp = new RegExp(id.regExp) }
});

export {
    ecbNatIDs
};
